
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myjavapp
  name: myweb
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myjavapp
  type: NodePort
